### PR TITLE
Fix word repitition in 'src/index.md'

### PR DESCRIPTION
**Pull request by vipranarayan14**
Replace 'makefile makefile' with 'makefile'.

### CODE REVIEW

**Comment by chaselambda** [comment]
Thank you!

**Comment by vipranarayan14** [comment]
👍

**Comment by vipranarayan14** [comment]
BTW, thank you for this wonderful tutorial. I was able to understand "the mysteries of the Makefile" very easily. I went from novice to intermediate Makefile user in 1 hr. Thanks again.

**Comment by chaselambda** [comment]
My pleasure!

**Pull request merged**
